plasma-umass/scalene

- scalene/scalene.py
'eval/compile' gives no `f_code.co_filename`. We have to look back into the outer frame in order to check the `co_filename`. Hence a line is added to look back by one frame if the `co_filename` is empty. This fixes #6 .
> Fix #6 Handle 'eval/compile' by accessing the outer frame

- scalene/scalene.py
The attribute 'current_footprint' is missing. Add it in the declaration of instance variables. This fixes #8 .
> Fix #8 Add the declaration of variable current_footprint

- scalene/scalene.py
Usage example for linux had a .dylib extension instead of .so
Used dedent to have nicer formatting of the usage string.
> Fix usage example for linux.

- scalene/scalene.py
Slightly modifies the output handling of scalene to:
1. Avoid reading the entire source file into memory, instead processing it line by line.
2. Use enumerate to track the line number.
3. Use str.rstrip to more reliably remove all trailing whitespace.
4. Fixes a possible divide by zero.  If `this_cpu_samples` is zero then the expression for `percent_cpu_time` will evaluate to zero anyway. Further down, there is a check for `Scalene.total_cpu_samples` being zero.  I'm guessing what was meant to be checked here was `Scalene.total_cpu_samples`.
> Output handling improvements

- pytest.ini
The files into test folder not follow the naming convetion for pytest
module. So, when we run directly `python3 -m pytest test` or
`python3 setup.py test` 0 test run. This can be complicated when we try
to packaging, i.e. Debian.
In this PR propose the creation of a python.ini file to find the files
inside the test folder with the *.py naming.
> Add pytest.ini to run tests successfuly

- README.md
Per request in #54, this adds instructions for using the AUR package to the README.
> Add Arch Linux installation instructions to README

- .gitignore
- MANIFEST.in
- Pipfile
- Pipfile.lock
- scalene/adaptive.py
- scalene/scalene.py
- scalene/sparkline.py
- test/test_sparkline.py
My first PR to Scalene. 😄 
1. The `Adaptive` class existed in both `adaptive.py` and `scalene.py`. I replaced the class in `adaptive.py` with the one from `scalene.py` and imported it.
1. Sparkline refactorings
1. I moved all the code related to Sparkline into it's own module, and created a class.
1. The `generate_sparkline` method is also moved from the `Scalene` class to the `Sparkline` class in order to give the `Scalene` class less responsibilities.
1. I created some tests for the Sparkline functionality
I'm looking forward to your comments.
Kind regards,
Johan Vergeer
> Cleanup duplicates and refactor sparkline

- scalene/__main__.py
Problems that occur when calling `scalene.Scalene.main` should not be swept under the rug, but should be exposed as an error and trigger a non-zero exit code.
I'm not 100% sure the proposed change is OK, but the current code was very effective at hiding a problem with my installation of `scalene` 1.1.1 (see #76).
> expose errors when calling main

- scalene/scalene.py
I've been debugging a case where libscalene.so gets a SIGSEGV. In this case, no error message is printed, but the main process just exits -11.  I suggest these changes to clarify what is going on.
> Adding error message in case subprocess receives a signal

- benchmarks/benchmark.py
- scalene/__main__.py
- scalene/entrypoint.py
- scalene/scalene_profiler.py
Renamed `scalene.py` to `entrypoint.py` to prevent some conflicts observed in importing with benchmarks. Made benchmark import relative. Added in `ReplacementPollSelector` to avoid dropped signals in long-running `poll`s.
> Fix naming conflicts and add in poll shim

- scalene/scalene_profiler.py
- test/issues/test-issue193.py
In addition to using `getattr()` instead of dot notation, this PR also removes the exception handler introduced by cd5b7e7, because it seems like a `KeyError` could only originate here if the `f_locals` dict changes between the membership test and the indexing operation. That _might_ be possible, but would be better addressed by accessing `f_locals` only once and caching the result.
> Bugfix/cautious attribute retrieval (closes #193)

- GNUmakefile
- scalene/scalene_preload.py
- scalene/scalene_profiler.py
Note that `libscalene.dylib` and `libscalene.so` are no longer generated at the top level directory, but directly into `scalene`. The homebrew formula may need to be adjusted.
> Fixes libscalene preloading, DRYes some code duplications

- .github/workflows/release-pypi-upload.yml
- README.md
- scalene/scalene_profiler.py
- scalene/scalene_version.py
- setup.py
Also raises the Python version requirement to 3.8 on Windows.
> Reverted to using signal.raise_signal on Windows

- scalene/scalene_magics.py
- scalene/scalene_output.py
- scalene/scalene_parseargs.py
- scalene/scalene_preload.py
- scalene/scalene_profiler.py
- scalene/scalene_sigqueue.py
- scalene/scalene_statistics.py
- vendor/README.md
Still not mypy-clean, but it turned up the mismatch that gets reported by https://github.com/plasma-umass/scalene/issues/250, where for some reason it doesn't look like `ScaleneStatistics.start_clock` is ever invoked. Moved some stuff to use `pathlib` which is cleaner than using strings and avoids the need to cast the alias directory to `Filename` (which was never quite right anyway).
> Changes to get fewer errors from `mypy`

- scalene/scalene_output.py
The previous logic would print a header even if it did not print any lines with significant memory consumption; this PR fixes this behavior.
> Fixed logic: don't print header when no significant memory culprits; replaced numbers w/variables

- scalene/scalene_preload.py
- scalene/scalene_statistics.py
- scalene/scalene_version.py
- src/include/sampleheap.hpp
- src/source/libscalene.cpp
Dramatically reduces overhead by using `pymalloc` (Python's built-in small object allocator) for most requests and instead tracking `mmap` requests for arena refills. Maintains previous accuracy for large object requests (> 512 bytes); seems to work surprisingly well even for large numbers of small object requests.
> Pymalloc mmap sampling

- .github/workflows/release-pypi-upload.yml
- GNUmakefile
- setup.py
- src/include/py_env.hpp
- src/source/libscalene.cpp
Updated build & upload workflow as well as other files as needed to build with the new code using the Python allocator API:
- builds can't use the restricted API anymore because there is no API call to get the executing file name; with that, they need to be built for each Python version;
- builds on MacOS aren't currently universal because we're linking directly with `libpython`, and that isn't universal;
This also fixes the `.devN` file naming for testing to `testpypi`. The MacOS wheels aren't currently working because `libpython` usually isn't found. Building for Windows is future work.
> F202109 wheels using memory apis

- scalene/scalene_json.py
- scalene/scalene_output.py
- scalene/scalene_profiler.py
- scalene/scalene_statistics.py
This PR corrects a problem with Scalene's memory attribution, where it could potentially dramatically over-report the amount of memory allocated by a line of code.
Prior to this PR, Scalene only tracked _total_ memory allocations per line. This approach doesn't work well when executing native code that itself is allocating and freeing a lot of memory, since it potentially exaggerates the amount of memory consumed by that line. In the worst case, a line of code could have a max footprint of 1 object (malloc-free-malloc-free...), but Scalene would report _N_ objects as the footprint.
This PR fixes this situation by tracking (sampled) frees whenever we are tracing a line of code (which we already do to count the number of distinct executions of a sampled line of code).
Normally, Scalene has …
> Update stats handling to track average peak per line.

- scalene/scalene_output.py
Without this you'd get a
```
TypeError: add_row() got an unexpected keyword argument 'end_section'
```
The output with this diff on rich 9.2.0 still looks fine to me.
[Airflow 2.0.0 for instance still requires rich 9.2.0](https://github.com/apache/airflow/blob/2.0.0/setup.cfg#L129), for instance, so I'd say there's still reason to support rich down to that version.
> Fixes incompatibility with rich < 9.4.0

- src/include/sampleheap.hpp
- src/source/libscalene.cpp
The Scalene allocator was calling `register_malloc` twice, once in `MakeLocalAllocator` and once in `SampleHeap`. However, it only registered a single `free`. This fix suppresses the write inside of `SampleHeap` so that the only one is in `MakeLocalAllocator`
> Fixed double-counting newlines

- scalene/scalene_arguments.py
- scalene/scalene_parseargs.py
- scalene/scalene_preload.py
- scalene/scalene_profiler.py
- scalene/scalene_statistics.py
- src/include/sampleheap.hpp
- src/source/libscalene.cpp
The allocation sampling window can now be changed at invocation time via the `--allocation-sampling-window` flag. Larger windows improve performance, at the cost of lower granularity peak reporting.
> Added `--allocation-sampling-window`; fixed reporting of peak function summary

- scalene/scalene_profiler.py
Fixed an anomalous loop condition that I suspect caused #201 as well as several other bits of weirdness. Logic was supposed to be "If code in a special block such as `<module>` or `<listcomp>`, keep going back in the stack until you find real code", but this logic has been around for a long time.
> Fixed scalene looping infinitely in some functions

- GNUmakefile
- src/include/memcpysampler.hpp
- src/include/sampleheap.hpp
- src/include/scaleneheader.hpp
Fixes #360 -- A highly network-bound program was running into `SIGSEGV`s. Inspection in `gdb` revealed that this was a double free happening in the arena allocator. In the process of adding a new arena, the array of arenas was being reallocated with `PyMem_RawRealloc`, and because `realloc` was previously overloaded as a composition of `malloc` and `free`. At some point in the middle of this, `SampleHeap::process_malloc` was being called, which called `whereInPython`, which queries the Python interpreter, which in turn allocates memory and creates a new arena, which requires expanding the list of arenas. This means that the list being `realloc`ed is freed in the middle of the call to `realloc`, leading to a double free. The solution to this was to [add the ability to redefine `realloc` in …
> Add override of realloc to prevent reentrancy 

- src/include/scaleneheader.hpp
Added padding to header placed on scalene-allocated blocks to make `sizeof(ScaleneHeader)` 16. This is the maximum alignment that can be output by basic configurations of the Python interpreter, though 8 bytes seems to be most commonly used as per [the source code](https://github.com/python/cpython/blob/main/Objects/obmalloc.c#L855). Fixes #362 .
> Made Scalene allocator use 16 byte alignment

- README.md
Updated readme to remove duplicate lines because they are the same command for both ubuntu 18 and 20.
> Removed duplicate lines in readme 

- scalene/scalene_profiler.py
Null profiles used to not overwrite `profile.json`, which is incorrect behavior. This PR simplifies the logic and makes behavior more consistent.
> Fixed logic for handling null profiles

- scalene/replacement_get_context.py
- scalene/replacement_lock.py
In light of https://github.com/plasma-umass/scalene/issues/416, warn users of Scalene on Windows that it does not currently support use of `multiprocessing` on that platform.
> Multiprocessing not supported for win32 - yet

- scalene/scalene_json.py
- scalene/scalene_output.py
- scalene/scalene_profiler.py
- src/source/pywhere.cpp
Right now, changing the current working directory in the middle of profiling disrupts name resolution (and even triggers an `abort`). This PR resolves all file names using the original invocation path.
> Resolve paths according to original working directory.

- scalene/scalene_profiler.py
This is meant to express the following logic:
- When an allocation occurs, settrace should be called
- the settrace callback should be called when the next line executes. Between this and the next allocation, no newline records should be registered. This is reflected in the 
`__last_profiled_invalidated` variable, which is set when a newline record is emitted and unset when an allocation is made
- If the settrace callback has not been called and Scalene detects a line change has been detected
> Fixed logic in line invalidation

- scalene/scalene_json.py
- scalene/scalene_output.py
- scalene/scalene_profiler.py
Scalene now fails gracefully when it encounters a file name that does not correspond to a real file, like `<bootstrap something>`. Working on improving the handling the name of the input file to cope with invocations of files from a different directory than the current, or names containing `./` (for example).
> Fixed file handling

- README.md
- requirements.txt
- scalene/scalene-gui/index.html.template
- scalene/scalene_arguments.py
- scalene/scalene_magics.py
- scalene/scalene_parseargs.py
- scalene/scalene_preload.py
- scalene/scalene_profiler.py
- setup.py
Two changes:
1. Scalene now generates a single "self-contained" HTML payload (called `profile.html`) containing the profile, and then launches a web browser to load it. No more web server! This HTML file will soon replace the existing `--html` output, which just was an HTML version of the text CLI.
2. New command-line behavior (breaks past command-line slightly, because we will deprecate `--cpu-only`).
* `--cpu` will only profile CPU, not GPU (change of behavior from `--cpu-only`, which actually did both)
* `--cpu --gpu` will only profile CPU and GPU, not memory
* `--cpu --memory` will only profile CPU and memory, not GPU
* `--cpu --gpu --memory` profiles everything - this is the same as specifying nothing
Two notes:
1. Windows currently doesn't support memory profiling, and Mac does not …
> Generate HTML instead of using a webserver; rationalizes metrics (--cpu, --gpu, and --memory)

- scalene/scalene_profiler.py
- test/issues/test-issue126.py
- test/issues/test-issue244.py
Fixes #126
By setting `sys.executable` to an absolute path.
---
Fixes #391 
Fixes #244
By replacing `-m some.module` by the path to this module (eg `/usr/lib/python3.10/site-packages/some/module.py` or `/usr/lib/python3.10/site-packages/some/module/__main__.py`).
---
Let me know if you have any suggestions/questions.
> Improve multiprocessing and module support

- scalene/scalene_profiler.py
- src/source/pywhere.cpp
After seeing performance issues, we reverted the previous attempt at introducing this new tracer. The main missing element in the old version of the C settrace callback was not marking irrelevant
frames as irrelevant, which has been resolved. This involves making some assumptions about the memory layout of 3.11+ `PyFrameObject`s﻿. In a worst-case scenario program,
`test/expensive_benchmarks/bm_pprint.py`, this change achieves more than a 2x speedup compared to the original implementation.
> Fixed algorithmic issues in C tracing

- GNUmakefile
This PR adds a `clear-vendor-dirs` target to `GNUMakefile` to prevent stale vendored dependencies, see #509 for details.
> Add and use clear-vendor-dirs target to prevent stale vendored deps (closes #509)

- GNUmakefile
- setup.py
- src/source/pywhere.cpp
This PR addresses a Windows compatibility issue and an inconsistency between two implementations of the `should_trace` in the C++ vs. the Python code. One thing that `should_trace` does is filtering out Python libraries, so Scalene doesn't profile Python itself. The C++ version of `should_trace` in `pywhere.cpp` uses hard-coded Unix/Mac OS X path separators (`/`) while the Python version correctly uses platform-specific separators. This PR builds paths with the platform-appropriate separators. The C++ version also now filters out Anaconda libraries, matching the functionality of the Python version.
> Fix C should_trace to support OS-specific path separators

- scalene/scalene_profiler.py
This PR replaces the manual ad hoc Python library exclusion logic with a call to `sysconfig` to get the library path, and uses `pathlib` to fully resolve it. In theory, this should "always work" and remove the need for listing individual cases.
> Generalize `should_trace`: use `sysconfig` to find Python library path

- scalene/scalene-gui/scalene-gui.js
This PR updates the web GUI to make it more manageable for profiles comprising many files.
Profiles are now individually collapsible (can be shown or hidden). As before, files are ordered from most to least CPU time. The first file is open by default. An example screenshot is shown below. Clicking on a triangle toggles the display of each profile; users can also click on "show all" and "hide all".
> Adds collapsible profiles to web GUI

- scalene/scalene_json.py
- scalene/scalene_profiler.py
Outputs a complete profile by preventing the JSON output processor from skipping lines that have no data.
Closes #434.
> Save full context in json when --reduced-profile is unset (#434)

- scalene/scalene_profiler.py
Fixed the bug from https://stackoverflow.com/questions/74606510/scalene-an-exception-of-type-unicodeencodeerror
Got the same error related to cp1250. Set in scalene_profiler.py the concrete encoding="utf-8"
> fixed encoding problem

- scalene/scalene_json.py
- scalene/scalene_profiler.py
- scalene/scalene_statistics.py
For now, this data is only in the JSON output, and not exposed to the UI. In the context of functions using multi-threaded libraries like `numpy` (and libraries built on it, like `pandas`), low core utilization should be a strong signal of poor vectorization.
> Added core utilization tracking (utilization across all cores).

- scalene/scalene_analysis.py
This should address https://github.com/plasma-umass/scalene/issues/587 which has more information, but basically the check for native fails on at least my system because package.__file__ exists, but is None, so os.path.dirname() returns a TypeError.
> Add handling of TypeError case to is_native

- .github/workflows/test-smoketests.yml
- scalene/scalene_json.py
- scalene/scalene_profiler.py
- test/profile_annotation_test.py
- test/smoketest.py
- test/smoketest_profile_decorator.py
Fixes to restore the `@profile` decorator to its intended semantics (if any code has a `@profile` decorator, only profile that code).
> Updates to properly handle @profile decorators for CPU time attribution

- GNUmakefile
This definition will break STL string, starting from GCC13.
Although GCC13 will not being widely used soon, we have encountered such problem on Arch Linux for loong64.
> Remove vsnprintf definition from printf.h

- scalene/scalene_profiler.py
Executing `os.chdir` in the Python script was causing output to go to the then-current directory instead of the invoked directory (if it was a relative path).
Fixes https://github.com/plasma-umass/scalene/issues/598.
> Immediately resolve output filename so it ends up in expected location

- .github/workflows/build-and-upload.yml
This PR upgrades [manylinux](https://github.com/pypa/manylinux) building from 2_24, which has reached EOL, and also adds building on `manylinux2014`, so as to resolve #670.
There seem to be pros and cons to both manylinux2014 and manylinux_2_28, with groups of users able to use the one but not the other, so we're generating both versions now and letting `pip` pick what it will.
> Upgrades manylinux building to 2_28, and adds manylinux2014

- scalene/scalene_profiler.py
Fixes Scalene behavior for the following test case:
```Python
import os
from django.conf import settings
from django.core.wsgi import get_wsgi_application
from django.http import HttpResponse
from django.urls import path
settings.configure(
DEBUG=True,
ROOT_URLCONF=__name__,
SECRET_KEY=os.urandom(32),
ALLOWED_HOSTS=['*'],
WSGI_APPLICATION='__main__.application',
)
def hello_world(request):
return HttpResponse("Hello, Django!")
urlpatterns = [
path('', hello_world),
]
application = get_wsgi_application()
if __name__ == "__main__":
from django.core.management import execute_from_command_line
execute_from_command_line([__file__, 'runserver'])
```
> Moved up assignment so __profiler_base is always defined.

- scalene/scalene_profiler.py
Using lambda only adds overhead and is less idiomatic.
> Simplify __functions_to_profile construction.

- scalene/scalene_analysis.py
`join` takes an iterable, so passing the result of `map` works and doesn't incur extra memory and CPU cost required to construct `list`.
> Remove unnecessary list creation in scalene_analysis.py

- scalene/scalene_json.py
This override is a noop, since `samples` is not used below, but is somewhat confusing and adds extra overhead.
> Remove unnecessary argument override.

- scalene/sparkline.py
`min` [supports](https://docs.python.org/3/library/functions.html#min) both iterable and scalar args and creating list is not free, so passing args directly is more efficient.
```python
In [16]: %timeit min([1, 2])
121 ns ± 0.0535 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
In [17]: %timeit min(1, 2)
96.2 ns ± 0.245 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
> [perf] Speed up spark creation in sparkline.

- scalene/sparkline.py
`samples` is constructed using list comprehension from `arr` so `len(samples) == len(arr)` is always `True` and consequently `samples == samples[: len(arr)]`. Even for small `arr` this slice creation still wastes resources:
```python
In [8]: arr = [-1, 0, 1, 2, 3, -2]
In [9]: samples = [i if i > 0 else 0.0 for i in arr]
In [10]: samples
Out[10]: [0.0, 0.0, 1, 2, 3, 0.0]
In [11]: samples[: len(arr)] == samples
Out[11]: True
In [12]: %timeit samples[:len(arr)]
82 ns ± 0.109 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
> Avoid unnecessary slice in sparkline.generate.

- scalene/scalene_analysis.py
- scalene/scalene_json.py
Added a new pair of fields to JSON, `start_outermost_loop` and `end_outermost_loop`, which keeps track of the outermost loop in the current scope that a given line belongs to. For instance,
```python
for i in a:
for j in b:
for k in c:
pass
```
The `pass` statement in the above snippet would be reported as being contained in the outermost for loop, which iterates over `i`. However,
```python
for i in a:
def b():
for j in c:
pass
```
the pass statement in the above snippet would be said to have an outermost for loop `for j in c:`, since the loop iterating over i is not in the same scope.
> Added outermost loop to JSON

- scalene/find_browser.py
- scalene/scalene_parseargs.py
- scalene/scalene_profiler.py
Ref: https://github.com/plasma-umass/scalene/issues/723
I tested by:
- Setting BROWSER to lynx and making sure it still defaulted to printing to the console instead of opening the html file.
- Setting BROWSER to vivaldi and making sure it did open the web view by default.
- Setting BROWSER to chromium and making sure it still opened the web view by default.
- Passing --cli with BROWSER=vivaldi to make sure it just printed to the console.
- Installing jupyter-lab to the venv, opening it, and running `%scrun` and `%%scalene` on some cells. I got the iframe to render with profile results.
> Handle text browsers explicitly to support unlisted GUI browsers

- scalene/scalene_profiler.py
This fixes a bug where the executable is invoked as `python3.10` (for example), and later a call to `subprocess.Popen` invokes a child using the executable name `python3`; because `python3` would not be created as an alias, capturing child process profiles did not work.
We should deprecate the `sys.executable` logic; I am only leaving it intact in case there is some edge case where using the obvious names does not work.
> Fix python aliases

- scalene/redirect_python.py
- scalene/scalene_profiler.py
- scalene/scalene_statistics.py
Factoring out logic to reduce the size of `scalene_profiler` and also help isolate any issues.
> Refactoring Python redirection

- scalene/scalene_profiler.py
- src/include/pywhere.hpp
- src/include/sampleheap.hpp
- src/source/libscalene.cpp
- src/source/pywhere.cpp
Fixes #487. Adds a flag, `p_scalene_done`, to libscalene that is updated by `pywhere`, which accesses it using `dlsym`. This is updated every time the corresponding flag is updated in the Python side of the profiler. 
This approach has two weaknesses:
1. There are two different flags here, one in Python-land and one in C-land. I can see no way this would cause issues, but it may be undesirable
2. Every time `p_scalene_done` is set, `dlsym` is called. For a high volume of calls to `scalene_profiler.start()` and `scalene_profiler.stop()`, this may incur significant overhead. I have seen no evidence of this sort of usage pattern from any users of Scalene that I have interacted with.
> Add scalene_done to pywhere

- .github/workflows/build-and-upload.yml
- .github/workflows/codeql.yml
- .github/workflows/test-smoketests.yml
This PR updates [actions/checkout](https://github.com/actions/checkout/releases/tag/v4.1.1) and [actions/setup-python](https://github.com/actions/setup-python/releases/tag/v5.0.0) to their respective latest versions.
> ci: update actions

- .github/workflows/test-smoketests.yml
- requirements.txt
This PR re-enables testing with Python 3.12 and addresses the [issue](https://github.com/plasma-umass/scalene/actions/runs/7561817150/job/20591132945) that was preventing CI from passing before.
Notable changes:
`lxml` updated to latest version to enable compatibility with py3.12
`pip` version lock is removed because we are using the latest version in CI through `python -m pip install --upgrade pip`
> ci: re-enable py3.12

- scalene/launchbrowser.py
- scalene/redirect_python.py
- scalene/scalene-gui/index.html.template
- scalene/scalene-gui/scalene-gui.js
- scalene/scalene_profiler.py
- scalene/scalene_utility.py
* Adds [Ollama](https://ollama.ai/) support (locally installed open source models).
* Now persists all chosen parameters (in class "persistent") in local storage.
* Spawns a web server to enable access to `localhost` when ollama is running locally. This won't work in settings where it's not possible to open a server, like Colab
TO DO:
* Test on Jupyter and other platforms
* Implement logic to support Amazon Bedrock usage.
> Adds support for "local" LLMs via ollama [WIP]

- GNUmakefile
GCC fails when building as it doesn't like the printf redefinition using ::write. Write apprently returns a value, even if nobody really wants it.
The addition of unused result checking caused all kinds of griping in the GCC userbase. This turns that check off globally. (Note, with the check on, the only failing line is the printf redefinition).
> Disable GCC's "unused-result" warnings

- scalene/find_browser.py
- scalene/launchbrowser.py
Simplifies the code by removing logic to pick from a set of known browsers. Launches using the system browser.
If this becomes a problem, we can always ask the user to supply a suitable one via the command line or print the launch URL to the console and have them click it. 
Fixes #778.
> Always use system browser

- scalene/replacement_signal_fns.py
- scalene/scalene_profiler.py
- scalene/scalene_signals.py
Added warning message when `start_profiling_signal` and `stop_profiling_signal` are used rather than failing immediately
> Handle signals more gracefully

- tests/test_coverup_109.py
- tests/test_coverup_17.py
- tests/test_coverup_2.py
Pytest emits a `PytestCollectionWarning` whenever it encounters a class whose name begins with `Test`. Setting `__test__ = False` in these classes resolves the issue.
See https://adamj.eu/tech/2020/07/28/how-to-fix-a-pytest-collection-warning-about-web-tests-test-app-class/
> Fix PytestCollectionWarning in tests

- scalene/scalene_parseargs.py
- test/issues/test-issue691.py
Adds check whether `args.outfiles` is a directory (and failing) immediately after parsing the args.
Fixes #691
> Ensure --outfile isn't a directory

- .github/workflows/test-smoketests.yml
- .github/workflows/tests.yml
- pyproject.toml
- setup.py
This PR adds a `pyproject.toml`, making our packaging PEP517 compatible.
I also cleaned up that kludgy way to set the platform for "-universal2" wheels on MacOS.
The MacOS 14 issues on GitHub remain, so I changed a couple of the matrix items for "tests" and "smoketests" to `macos-13` (so that I could test).  I didn't test the packaging separately on GitHub because the matrix there is more complex... I don't want to cause conflicts with anything that Sam may be working on for MacOS 14.
> Move packaging to PEP517 style

- GNUmakefile
- MANIFEST.in
- pyproject.toml
- scalene/scalene_json.py
- setup.py
- tests/test_coverup_85.py
crdp (C-version of the Ramer-Douglas-Peucker algorithm) is a Cython package, which requires the installer to have a C compiler. The pure Python version is far too slow. This PR removes crdp and replaces it with a numpy based version; it's still 50x faster than the pure Python version, though 2x slower than the Cython-compiled package.
> Removed crdp dependency.

- pyproject.toml
> Don't include nvidia-ml-py on MacOS (not supported)

- .github/workflows/test-smoketests.yml
- pyproject.toml
- requirements.txt
- scalene/scalene-gui/scalene-gui.js
- scalene/scalene_accelerator.py
- scalene/scalene_apple_gpu.py
- scalene/scalene_json.py
- scalene/scalene_neuron.py
- scalene/scalene_nvidia_gpu.py
- scalene/scalene_profiler.py
- scalene/scalene_statistics.py
- tests/test_coverup_32.py
Now reports device utilization (regardless of execution time) in pies for GPU/Neuron.
> Neuron + GPU: report utilization % of accelerators regardless of execution time

- scalene/scalene_profiler.py
This fixes https://github.com/plasma-umass/scalene/issues/841 by preventing the CPU signal (SIGALRM) from interrupting anything in `os`. In theory, this should not impact profiling of OS calls, since these block signal delivery anyway.
> Prevent signals interrupting anything in os.

- pyproject.toml
Missed this one: need to change in both requirements and pyproject.
> Remove setuptools pin from pyproject

- scalene/scalene-gui/scalene-gui.js
Adds time to tooltips which appear when hovering over time % breakdowns.
> Preliminary inclusion of time in tooltips

- scalene/scalene_profiler.py
Avoid overwriting output file with HTML. Fixes https://github.com/plasma-umass/scalene/issues/852.
> Fix output file json

- scalene/scalene_utility.py
As the title says, this PR make sure to record the fully qualified name of a function when saving data with `--stacks`.
It seems a good idea by itself, but in addition let me explain what is my personal use case for that.
I'd like to produce *per-function* flamegraphs: i.e., I want to ignore the line number reported by a each sample and consider only the function.
The problem is that the current code saves `co_name`, but in case of multiple function with the same name, there is no easy way to distinguish them [1]. This is something which happens quite often in case of a method overridden in multiple subclasses.
([1] I know that there are "hard ways": I could e.g. use the line number and walk backwards in the source code until I find a `def` statement, but this is slow, complicated and …
> record the fully_qualified_name when using --stacks

- scalene/scalene_preload.py
- scalene/scalene_profiler.py
- tests/test_coverup_5.py
Because of how the current environment is checked, `LD_LIBRARY_PATH` and `LD_PRELOAD` are squashed if present, rather than prepended to. This commit prevents this.
Also preemptively fixed a potential issue where `PYTHONMALLOC` would not be properly squashed if present.
> Fixed LD_LIBRARY_PATH squashing

- scalene/scalene_analysis.py
The previous regex (meant to eliminate Jupyter notebook 'magics'), in some edge cases, would cause parsing to fail (leading to an `IndentationError`). This PR updates the regex to prevent that from happening.
> Revised regex for magics removal

- scalene/scalene_profiler.py
Resolved memory accounting issue where the last_profiled invalidation queue was never getting non-null data from pywhere due to `malloc_signal_handler` squashing the `last_profiled` list.
> Fixed memory leak issues

- scalene/scalene_profiler.py
Scalene apparently needs to import `ctypes` early or some breakage occurs because of the change to `sys.executable` (needed to support multiprocessing). This fixes  https://github.com/plasma-umass/scalene/issues/894.
> Import `ctypes` early

- scalene/scalene_profiler.py
Turns out the issue https://github.com/plasma-umass/scalene/issues/539 still persists for deeply nested modules, e.g.:
```
scalene -m x.y.z
```
This PR fixes this behaviour by enhancing the solution introduced in https://github.com/plasma-umass/scalene/pull/646
> Fix module import issues for deeply nested modules (e.g., x.y.z).

- scalene/scalene_preload.py
It looks like in some cases setup_preload gets called more than once, so it was adding `libscalene.so` to `LD_PRELOAD` the first time then later replacing `LD_PRELOAD`  with just `libscalene.so`, this fixes that case.
> Fix for overwriting LD_PRELOAD if it contains libscalene.so and other values

- scalene/replacement_lock.py
- scalene/replacement_poll_selector.py
- scalene/replacement_signal_fns.py
- scalene/scalene_analysis.py
- scalene/scalene_json.py
- scalene/scalene_leak_analysis.py
- scalene/scalene_neuron.py
- scalene/scalene_nvidia_gpu.py
- scalene/scalene_profiler.py
- scalene/scalene_utility.py
Made modifications in light of Ruff's analysis.
> Ruff n ready

- .github/workflows/test-smoketests.yml
- scalene/scalene_profiler.py
- test/signal_test.py
Fixed user timer being disabled after it "rings" instead of being reset
> Fix signal timer resetting

- scalene/__main__.py
- scalene/scalene_profiler.py
- tests/test_coverup_125.py
- tests/test_coverup_131.py
- tests/test_coverup_133.py
- tests/test_coverup_24.py
- tests/test_coverup_53.py
- tests/test_coverup_73.py
- tests/test_coverup_78.py
- tests/test_coverup_84.py
- tests/test_coverup_88.py
- tests/test_coverup_90.py
Added privatization (preceding underscores) for clarity and later refactoring; used `[ssort](https://github.com/bwhmather/ssort)` to reorganize `scalene_profiler.py`. Moved a line to fix https://github.com/plasma-umass/scalene/issues/947..
> Cleanup; fixes https://github.com/plasma-umass/scalene/issues/947.
