plasma-umass/scalene

scalene/scalene.py
make it works under python3.5 as well.
=> Switch f-string to normal one

GNUmakefile
A simple condition to warn you if the directory is dirty before publishing.
I was too lazy so I grabbed the code from the first link google provided  (https://github.com/openclimatedata/pymagicc/blob/master/Makefile)
=> Warn before publish if directory is dirty

docs/README_CN.md
I have translated the README from English to Chinese.
It may be convenient for Chinese developers to know about scalene.
=> add docs/README_CN.md

scalene/__main__.py, scalene/scalene.py, setup.py
#3 Support console_scripts by adding an entry_points in setup.py.
=> Support console_scripts

scalene/scalene.py
=> fix PermissionError when no output file specified

MANIFEST.in
=> include files required to (re)build libscalene.so from source

include/sampleheap.hpp
Factored out file and lockfile handling of `SampleHeap`
=> Refactored SampleHeap to using SampleFile

README.md, scalene/scalene_output.py, scalene/scalene_profiler.py, scalene/scalene_statistics.py, setup.py
Using GPUtil to extract load; currently set to do this at 1/10th the CPU sampling rate to reduce overhead. Also fixed zero check for system time.
=> Added GPU profiling support.

scalene/replacement_lock.py
=> adds inheritance to replacement lock

heaplayers-make.mk, src/include/common.hpp, src/source/libscalene.cpp
**This PR is intended for discussion primarily. This hasn't been extensively tested, Sam is also working on the same thing, his version may be better, or have elements we could incorporate here, or we could find out we don't need these changes.**
=> Use Hoard as the allocator on MacOS.

scalene/scalene_profiler.py, test/multiprocessing_test.py
Added check in signal handler for other lock in threading
=> Added check for other internal lock

scalene/scalene_profiler.py
Fixed a race condition where fork was called while child threads are in their critical sections.
=> Fixed deadlock

src/source/libscalene.cpp
Requires [HeapLayers' PR #37.](https://github.com/emeryberger/Heap-Layers/pull/37)
=> - simplified code by reusing HL::OneHeap;

scalene/scalene_profiler.py
Also fixes `Scalene.__stats.start_clock()` not being called before re-enabling signals in `start()`.
=> Adds clearing of mmap'ed data that may have accumulated while profiling was stopped

scalene/scalene_output.py, scalene/scalene_profiler.py
Fixes `--profile-interval` when combined with multiprocessing and cleans up a few other small things.
=> F202106 interval with multiprocessing

.github/workflows/release-pypi-upload.yml, setup.py
=> F202107-windows-wheels

scalene/scalene_profiler.py
Moves initialization logic to `__init__` and exits if the requisite files are not found (plus some minor type annotation mods to make mypy happy).
=> Fail gracefully if there is a PID mismatch.

scalene/scalene_json.py
created 'functions' block with all function summary information
=> Added function summary field to JSON

scalene/scalene_profiler.py
Added a check to prevent illegal invocations of the Scalene API﻿
=> Added initialization check

scalene/scalene_profiler.py
=> Fix issue 272

scalene/scalene_arguments.py, scalene/scalene_parseargs.py, scalene/scalene_profiler.py
This PR adds a --port argument to specify the port bound by the local web server
=> Added --port cli argument

scalene/scalene_json.py
=> open file with encoding=utf-8

scalene/replacement_get_context.py, scalene/replacement_pjoin.py, scalene/replacement_signal_fns.py, scalene/scalene_apple_gpu.py, scalene/scalene_client_timer.py, scalene/scalene_preload.py, scalene/scalene_profiler.py, scalene/scalene_signals.py, scalene/scalene_statistics.py
Added some typing information to appease MyPy. WIP because there are still some issues as reported by mypy.
=> Resolve typing information

scalene/scalene_profiler.py
Added shallow copy of is_thread_sleeping table﻿ into cpu_sigqueue_processor
=> Fixed issue where is_thread_sleeping was accessed in wrong place

README.md
This adds a few bits of explanations about running scalene, specifically for my use case :)
I struggled to get it running, and had to find #244 and #397 to figure out how to do it.
It's the 4th time I've been trying to use `scalene`, so I felt like a bit of docs couldn't hurt!
=> Add explanations about running scalene in README

GNUmakefile, scalene/scalene_json.py, setup.py
This seems to build everywhere. Let's see if the tests run as well.
=> "vendored" crdp to reduce dependencies

scalene/scalene_json.py, scalene/scalene_profiler.py
Fixes https://github.com/plasma-umass/scalene/issues/520.
=> Eliminates binary file reading/writing and dependency on linecache.

scalene/scalene-gui/index.html.template, scalene/scalene-gui/scalene-gui.js
Initial, experimental support for proposed optimizations. (To my knowledge, this is the first integration of large language models into a profiler.)
To enable, first enter an [OpenAI key](https://beta.openai.com/signup) - click on "advanced options", then enter a key.
Once the key is entered, clicking on any line generates proposed optimizations. Click again for a new proposed optimization.
=> Adds AI-powered proposed optimizations

scalene/scalene_profiler.py
=> Testing fix for issue 540

scalene/scalene_profiler.py
This allows for arguments containing spaces.
=> Quote arguments to subprocesses

scalene/scalene-gui/scalene-gui.js, scalene/scalene_json.py
Fixes https://github.com/plasma-umass/scalene/issues/629.
=> Escape/unescape HTML/Unicode.

scalene/scalene_json.py
A solution for the Bug: An exception of type UnicodeEncodeError occurred.
=> Fix a Bug and Update scalene_json.py

scalene/replacement_mp_lock.py, scalene/replacement_poll_selector.py
=> Updated qualnames

scalene/scalene-gui/scalene-gui.js
Made changes so Scalene works with GPT-3.5 instead of GPT-3. Initial "pure Python" prompt added, not yet exposed in the API.
=> Moving to GPT-4.

scalene/scalene-gui/scalene-gui.js, scalene/scalene_profiler.py
Fixes https://github.com/plasma-umass/scalene/issues/642 and https://github.com/plasma-umass/scalene/issues/643 (same underlying issue).
=> Escape filenames for Windows

.github/workflows/build-and-upload.yml, GNUmakefile, setup.py
This should fix the current GitHub actions build issue.
=> Switches to using 'build' module

scalene/scalene_json.py, scalene/scalene_output.py, scalene/scalene_profiler.py
Adds an extra field to Scalene JSON with the invocation arguments
=> Added invocation arguments to json

scalene/scalene_magics.py, scalene/scalene_profiler.py
Fixes https://github.com/plasma-umass/scalene/issues/600.
=> Fixing Jupyter output file issue 

scalene/scalene-gui/scalene-gui.js
=> Added warning messages for insufficient funds in OpenAI account

scalene/scalene_gpu.py
It's much more efficient and more idiomatic.
=> [perf] Replace `append`s with list comprehension.

scalene/scalene_parseargs.py
This PR changes the `--viewer` command to open the UI from a local file instead of going to a hosted web page.
=> Change --viewer to open UI locally instead of from web.

scalene/scalene-gui/index.html.template, scalene/scalene-gui/scalene-gui.js, scalene/scalene_arguments.py, scalene/scalene_parseargs.py, scalene/scalene_profiler.py
This also fixes some issues with displaying Vega graphics that manifested upon switching to major versions of Vega and friends.
=> Added features for Scalene VS Code extension support

GNUmakefile
Fixes in https://github.com/plasma-umass/scalene/issues/699 (at least the first error).
=> Use the system temporary directory instead of `/tmp` on Unix/OS X

scalene/scalene_profiler.py
Fixes https://github.com/plasma-umass/scalene/issues/489.
=> Added support for command-line scripts.

scalene/scalene-gui/scalene-gui.js, scalene/scalene_json.py, scalene/scalene_profiler.py, scalene/scalene_statistics.py, scalene/scalene_utility.py
Prompt now directly incorporates Scalene performance information for lines or regions, work in progress.
Also fixed flamegraphs logic (since stack format changed, in preparation for eventual dynamic selection of code regions in the UI).
=> [WIP] Feedback-driven prompting

scalene/scalene_profiler.py
Resolves https://github.com/plasma-umass/scalene/issues/760.
=> Added more descriptive explanations for failed profiles.

scalene/scalene-gui/index.html.template, scalene/scalene-gui/scalene-gui.js
Present implementation supports openai and locally installed models to fetch code suggestions. As part of this PR, have added support to fetch code suggestions from azure open ai interfaces as well.
=> Added support for azure openai to fetch code suggestions

.github/workflows/build-and-upload.yml
Not sure if it is enough. Closes #807
=> Add Python 3.12 Wheel support

scalene/redirect_python.py
Fixes https://github.com/plasma-umass/scalene/issues/811.
=> Fix sys.executable handling for Windows

scalene/scalene_arguments.py, scalene/scalene_profiler.py, scalene/set_nvidia_gpu_modes.py, tests/test_coverup_53.py
There was some drift on Jupyter notebooks; this PR restores Jupyter functionality.
=> Fixing Scalene inside Jupyter notebooks

requirements.txt
=> Adds supporting packages for setuptools >= 71

pyproject.toml, scalene/scalene_json.py
Initial definition of JSON schema for Scalene's JSON payload, intended to help catch any JSON issues as well as to be more declarative.
=> Incorporated Pydantic JSON schema checking

src/include/traceconfig.hpp
Fixes https://github.com/plasma-umass/scalene/issues/869
=> Fix utf8 path handling

scalene/scalene_json.py
Fixes https://github.com/plasma-umass/scalene/issues/871.
=> Fix rounding issue in JSON validation

scalene/scalene_profiler.py, scalene/scalene_signal_manager.py
Moved logic into scalene_profiler to enable precise math computations
=> Geometric sampling update
